### PR TITLE
Pinning ceres solver

### PR DESCRIPTION
**Pull request by cduguet**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This pins the dependency of ceres-solver to 2.1.0, as it is necessary to run with pycolmap 0.4.0 and pixsfm 1.0.0. The issue is described in more detail in https://github.com/conda-forge/pixsfm-feedstock/issues/17.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @cduguet - I think what we really need to do is to create branches for colmap=3.8 and pycolmap=0.4.0 in the respective feedstocks (we can branch out from the latest commit before bumping the versions), and then rerender in these branches to get the latest versions of the dependencies. Then we will not need this hack here in pixsfm. Are you happy to give that a go? I'd be happy to help out if you take the initial steps.

**Comment by cduguet** [comment]
Thank you! 
I have forged both [pycolmap-feedstock](https://github.com/conda-forge/pycolmap-feedstock/) branching out at [a145937](https://github.com/conda-forge/cduguet/commit/a145937fbe590f9d6775ff44c5b6bfd771aba0ee). 
I am not sure if we need to pin colmap to 3.8, though, or if 3.9 is just fine. This one requires 3.9 from a patch, but it's not building (see more in [branch](https://github.com/cduguet/pycolmap-feedstock/tree/rebuilding_0.4.0), so I guess I'll start rebuilding colmap on 3.8 first.

**Comment by cduguet** [comment]
Forged [colmap-feedstock](https://github.com/cduguet/colmap-feedstock/) branching out from [0c1c754](https://github.com/cduguet/colmap-feedstock/commit/0c1c7543dc97ede84e3fcf88e1fc517fb01b9c2d) on [rebuilding_3.8](https://github.com/cduguet/colmap-feedstock/tree/rebuilding_3.8). Currently building locally to see if it works.

**Comment by Tobias-Fischer** [comment]
Hi @cduguet - are you happy to create a branch for pycolmap 0.4.0 so resolve this?

**Comment by cduguet** [comment]
I just created a [PR](https://github.com/conda-forge/pycolmap-feedstock/pull/26) to the [dev branch](https://github.com/conda-forge/pycolmap-feedstock/tree/dev) of [pycolmap-feedstock](https://github.com/conda-forge/pycolmap-feedstock), branching out from the latest commit for 0.4.0, which was [ad4d043](https://github.com/cduguet/pycolmap-feedstock/commit/ad4d043491de99f8d27c0dcff8c7bd04241ca978).

**Comment by karthik101200** [comment]
> I just created a [PR](https://github.com/conda-forge/pycolmap-feedstock/pull/26) to the [dev branch](https://github.com/conda-forge/pycolmap-feedstock/tree/dev) of [pycolmap-feedstock](https://github.com/conda-forge/pycolmap-feedstock), branching out from the latest commit for 0.4.0, which was [ad4d043](https://github.com/cduguet/pycolmap-feedstock/commit/ad4d043491de99f8d27c0dcff8c7bd04241ca978).

Im sorry this all seems a bit confusing to me but is it possible now to install pycolmap 0.4.0 with ceres 2.1.0 because i think ceres 2.2.0 results in keypoint adjustment giving me this error 
`TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pixsfm._pixsfm._keypoint_adjustment.TopologicalReferenceKeypointOptimizer(arg0: pixsfm._pixsfm._keypoint_adjustment.TopologicalReferenceKeypointOptimizerOptions, arg1: pixsfm._pixsfm._keypoint_adjustment.KeypointAdjustmentSetup, arg2: pixsfm._pixsfm._base.InterpolationConfig)
Invoked with: {'loss': {'name': 'cauchy', 'params': [0.25]}, 'solver': {'function_tolerance': 0.0, 'gradient_tolerance': 0.0, 'parameter_tolerance': 1e-05, 'minimizer_progress_to_stdout': False, 'max_num_iterations': 100, 'max_linear_solver_iterations': 200, 'max_num_consecutive_invalid_steps': 10, 'max_consecutive_nonmonotonic_steps': 10, 'use_inner_iterations': False, 'use_nonmonotonic_steps': False, 'update_state_every_iteration': False, 'num_threads': 1}, 'print_summary': False, 'bound': 2.0, 'num_threads': -1}, <pixsfm._pixsfm._keypoint_adjustment.KeypointAdjustmentSetup object at 0x7fa1a98defb0>, {'nodes': [[0.0, 0.0]], 'mode': 'BICUBIC', 'l2_normalize': True, 'ncc_normalize': False, 'use_float_simd': False}`

**Comment by Tobias-Fischer** [comment]
Just merged #23 - I hope this has resolved this issue

**Pull request closed without merging**
